# Active public executor for `devmake apply`.
# Public output contract changes should land here unless there is an explicit
# migration to a different apply path.
from pathlib import Path

from forgestack.core.template_loader import render_template_text


def _safe_target_path(output_root: Path, relative_path: str) -> Path:
    candidate = (output_root / relative_path).resolve()
    root = output_root.resolve()

    if candidate != root and root not in candidate.parents:
        raise RuntimeError(f"Unsafe output path outside project root: {relative_path}")

    return candidate


def execute_plan(plan, output_root=Path(".")):
    output_root = Path(output_root)
    render_context = getattr(plan, "render_context", {}) or {}

    seen_file_targets = set()

    for action in plan.actions:
        action_type = action.get("type")
        if action_type not in {"create_file", "create_directory"}:
            raise RuntimeError(f"Unsupported plan action type: {action_type}")

        relative_path = action.get("path")
        if not relative_path:
            raise RuntimeError("Plan action missing required 'path'")

        if action_type == "create_file":
            if relative_path in seen_file_targets:
                raise RuntimeError(f"Duplicate file target in plan: {relative_path}")
            seen_file_targets.add(relative_path)

            path = _safe_target_path(output_root, relative_path)

            content = action.get("content")
            template_name = action.get("template")

            if content is None and template_name:
                content = render_template_text(template_name, render_context)

            if content is None:
                content = "# generated by ForgeStack\n"

            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")

            print(f"create {path}")

        elif action_type == "create_directory":
            path = _safe_target_path(output_root, relative_path)
            path.mkdir(parents=True, exist_ok=True)

            print(f"mkdir  {path}")