import os


def execute_plan(plan):

    for action in plan.actions:

        if action["type"] == "create_file":

            path = action["path"]
            content = action.get("content") or f"# generated by ForgeStack\n"

            directory = os.path.dirname(path)

            if directory:
                os.makedirs(directory, exist_ok=True)

            with open(path, "w", encoding="utf-8") as f:
                f.write(content)

            print(f"create {path}")