from pathlib import Path

from forgestack.core.template_loader import load_template_text


def execute_plan(plan, output_root=Path(".")):
    output_root = Path(output_root)

    for action in plan.actions:
        if action["type"] == "create_file":
            path = output_root / action["path"]

            content = action.get("content")
            template_name = action.get("template")

            if content is None and template_name:
                content = load_template_text(template_name)

            if content is None:
                content = "# generated by ForgeStack\n"

            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

            print(f"create {path}")

        elif action["type"] == "create_directory":
            path = output_root / action["path"]
            path.mkdir(parents=True, exist_ok=True)

            print(f"mkdir  {path}")