from forgestack.core.registry import PluginRegistry
from forgestack.core.planner import create_plan
from forgestack.core.stack_loader import load_stack_yaml, get_plugin_names
from forgestack.core.preset_resolver import resolve_document
from forgestack.cli.main import _build_render_context
from forgestack.core.plan_executor import execute_plan


def test_generated_structured_workflow_vertical_slice(tmp_path):
    raw_doc = load_stack_yaml("projects/PipelineWorkbenchApp.yaml")
    effective_doc = resolve_document(raw_doc)
    plugin_names = get_plugin_names(effective_doc)
    render_context = _build_render_context(raw_doc, effective_doc)

    registry = PluginRegistry()
    registry.discover()

    _, plan = create_plan(plugin_names, registry, render_context=render_context)
    output_root = tmp_path / "PipelineWorkbenchApp"
    execute_plan(plan, output_root=output_root)

    app_config = (output_root / "backend" / "app_config.py").read_text(encoding="utf-8")
    compose = (output_root / "docker-compose.yml").read_text(encoding="utf-8")
    frontend_shell = (output_root / "frontend" / "src" / "generated" / "AppShell.jsx").read_text(encoding="utf-8")

    env_example = (output_root / ".env.example").read_text(encoding="utf-8")
    readme = (output_root / "README.md").read_text(encoding="utf-8")


    pipelines_readme = (output_root / "pipelines" / "README.md").read_text(encoding="utf-8")
    pipelines_init = (output_root / "pipelines" / "__init__.py").read_text(encoding="utf-8")
    sample_pipeline = (output_root / "pipelines" / "sample_pipeline.py").read_text(encoding="utf-8")

    data_readme = (output_root / "data" / "README.md").read_text(encoding="utf-8")
    data_gitkeep = output_root / "data" / ".gitkeep"

    conf_readme = (output_root / "conf" / "README.md").read_text(encoding="utf-8")
    conf_base_parameters = (output_root / "conf" / "base" / "parameters.yml").read_text(encoding="utf-8")
    conf_local_readme = (output_root / "conf" / "local" / "README.md").read_text(encoding="utf-8")

    assert '"project_name": "PipelineWorkbenchApp"' in app_config
    assert '"stack_name": "structured-workflow-stack"' in app_config
    assert '"app_name": "pipeline-workbench"' in app_config

    assert '"workflow": {' in app_config
    assert '"enabled": True' in app_config
    assert '"engine": "kedro"' in app_config
    assert '"pipeline_root": "pipelines"' in app_config
    assert '"config_root": "conf"' in app_config
    assert '"data_root": "data"' in app_config
    assert '"sample_pipeline": "sample_pipeline"' in app_config
    assert '"stages": ["ingest", "transform", "report"]' in app_config

    assert '"jupyter": {' in app_config
    assert '"port": 8888' in app_config

    assert "jupyter:" in compose
    assert "jupyter/base-notebook:python-3.11" in compose
    assert '"8888:8888"' in compose
    assert "postgres:" not in compose
    assert "redis:" not in compose
    assert "celery:" not in compose

    assert "Pipeline Workbench" in frontend_shell
    assert "Workflow Overview" in frontend_shell
    assert "Pipeline Assets" in frontend_shell
    assert "Pipeline Stages" in frontend_shell
    assert "Data Staging" in frontend_shell
    assert "Future Pipeline Actions" in frontend_shell
    assert "Notebook Workspace" in frontend_shell
    
    assert "# Pipelines" in pipelines_readme
    assert "Structured workflow pipeline package generated by ForgeStack." in pipelines_init
    assert "def describe_pipeline()" in sample_pipeline
    assert '"name": "sample_pipeline"' in sample_pipeline
    assert '"status": "scaffold"' in sample_pipeline

    assert "# Data" in data_readme
    assert data_gitkeep.exists()

    assert "# Configuration" in conf_readme
    assert "pipeline_name: sample_pipeline" in conf_base_parameters
    assert "run_mode: local" in conf_base_parameters
    assert "# Local Configuration" in conf_local_readme

    assert "JUPYTER_PORT=8888" in env_example
    assert "POSTGRES_" not in env_example
    assert "REDIS_" not in env_example

    assert "- Notebook Workspace: Jupyter" in readme
    assert "- Database: SQLite" in readme
    assert "- Cache/Queue: Redis" not in readme
    assert "- Worker: Celery" not in readme
