"""
Sample structured workflow pipeline scaffold.

This file is a lightweight placeholder for future Kedro-style or
pipeline-oriented workflow definitions generated by ForgeStack.
"""


def describe_pipeline():
    return {
        "name": "sample_pipeline",
        "status": "scaffold",
        "stages": [
            "ingest",
            "transform",
            "report",
        ],
    }